[build]
builder = "DOCKER"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
FLASK_ENV = "production"
PYTHON_VERSION = "3.11" 