services:
  - type: web
    name: stock-prediction-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: RAPIDAPI_HOST
        value: yahoo-finance15.p.rapidapi.com 